
drop table if exists USERS;
CREATE TABLE USERS (
  USER_ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Auto generated id for a user',
  USERNAME varchar(255) NOT NULL unique COMMENT 'User name for the User',
  PASSWORD varchar(255) NOT NULL COMMENT 'Hashed Password of the user',
  EMAIL varchar(255) NOT NULL COMMENT 'Email address of the User',
  STATUS int(11) DEFAULT NULL COMMENT 'Status can be new, etc',
  ENABLED BOOLEAN NOT NULL COMMENT '',
  CREATED_BY varchar(255) DEFAULT NULL,
  CREATED_TIME timestamp NULL DEFAULT NULL,
  UPDATED_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID) USING HASH
);

drop table if exists AUTHORITIES;
CREATE TABLE AUTHORITIES (
    USERNAME varchar(255) not null,
    AUTHORITY varchar(50) not null,
    CREATED_BY varchar(255) DEFAULT NULL,
    CREATED_TIME timestamp NULL DEFAULT NULL,
    UPDATED_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
create unique index idx_auth_username on authorities (username,authority);

CREATE TABLE SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BLOB NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

drop table if exists POST;
CREATE TABLE POST(
    POST_ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Auto generated id for a Post',
    TITLE varchar(255) NOT NULL COMMENT 'Title of the Post',
    BODY MEDIUMTEXT COMMENT 'All the text',
    CREATED_BY varchar(255) DEFAULT NULL,
    CREATED_TIME timestamp NULL DEFAULT NULL,
    UPDATED_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (POST_ID) USING HASH
);

